version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/frontend"
      - "/backend"
      - "/infra"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/backend/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
